import streamlit as st
st.image(https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXIycHNnOWZmdGhxZm9oc2tnZzYydGJ0MnltNm1iYTVsajZhemZ3NiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fdHEuiq2E0PKwxbCLr/giphy.gif)
